import {
  Document,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  AlignmentType,
  Packer,
  ShadingType,
  Footer,
  PageNumber,
} from "docx";
import crypto from "crypto";

export interface DocxSection {
  heading: string;
  paragraphs: string[];
  bulletPoints?: string[];
}

export interface DocxTableData {
  headers: string[];
  rows: string[][];
}

export interface DocxReportOptions {
  title: string;
  subtitle?: string;
  authorName?: string;
  authorEmail?: string;
  classification?: string;
  executiveSummary: string;
  sections: DocxSection[];
  tableData?: DocxTableData;
  actionItems?: string[];
  securityScore?: number;
}

export async function generateExecutiveDocx(options: DocxReportOptions): Promise<{ buffer: Buffer; hash: string }> {
  const {
    title,
    subtitle = "Strategic Sovereign AI Audit & Executive Brief",
    authorName = "NEXA AI Sovereign OS",
    authorEmail = "governance@nexa.ai",
    classification = "CONFIDENTIAL // USER-GOVERNED AI OPERATING SYSTEM",
    executiveSummary,
    sections,
    tableData,
    actionItems = [
      "Review AI Constitution boundary enforcements across all sub-agents.",
      "Ratify recommended policy amendments in the Governance Center.",
      "Archive verified episodic memory vectors into persistent storage.",
    ],
    securityScore = 100,
  } = options;

  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const integritySeed = `${title}|${authorEmail}|${dateStr}|${Date.now()}`;
  const sha256Hash = crypto.createHash("sha256").update(integritySeed).digest("hex");

  const borderCyan = {
    top: { style: BorderStyle.SINGLE, size: 8, color: "0891B2" },
    bottom: { style: BorderStyle.SINGLE, size: 8, color: "0891B2" },
    left: { style: BorderStyle.SINGLE, size: 24, color: "0891B2" },
    right: { style: BorderStyle.SINGLE, size: 8, color: "0891B2" },
  };

  const tableBorderLight = {
    top: { style: BorderStyle.SINGLE, size: 4, color: "CBD5E1" },
    bottom: { style: BorderStyle.SINGLE, size: 4, color: "CBD5E1" },
    left: { style: BorderStyle.SINGLE, size: 4, color: "CBD5E1" },
    right: { style: BorderStyle.SINGLE, size: 4, color: "CBD5E1" },
  };

  const docChildren: any[] = [
    // Header Banner / Classification
    new Paragraph({
      alignment: AlignmentType.RIGHT,
      children: [
        new TextRun({
          text: classification,
          size: 16, // 8pt
          bold: true,
          color: "0891B2",
          font: "Segoe UI",
        }),
      ],
      spacing: { after: 200 },
    }),

    // Document Title
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [
        new TextRun({
          text: title,
          bold: true,
          size: 52, // 26pt
          color: "0F172A",
          font: "Segoe UI",
        }),
      ],
      spacing: { after: 120 },
    }),

    // Subtitle
    new Paragraph({
      children: [
        new TextRun({
          text: subtitle,
          size: 26, // 13pt
          color: "475569",
          italics: true,
          font: "Segoe UI",
        }),
      ],
      spacing: { after: 280 },
    }),

    // Metadata Strip
    new Paragraph({
      children: [
        new TextRun({ text: "Generated By: ", bold: true, size: 18, color: "334155" }),
        new TextRun({ text: `${authorName} (${authorEmail})   |   Date: `, size: 18, color: "64748B" }),
        new TextRun({ text: `${dateStr}   |   Integrity Grade: `, size: 18, color: "64748B" }),
        new TextRun({ text: `GRADE A (${securityScore}%)`, bold: true, size: 18, color: "0891B2" }),
      ],
      spacing: { after: 360 },
    }),

    // Executive Summary Callout Box
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({
          children: [
            new TableCell({
              borders: borderCyan,
              shading: { type: ShadingType.CLEAR, fill: "F8FAFC" },
              margins: { top: 200, bottom: 200, left: 240, right: 200 },
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: "EXECUTIVE SUMMARY",
                      bold: true,
                      size: 20, // 10pt
                      color: "0891B2",
                      font: "Segoe UI",
                    }),
                  ],
                  spacing: { after: 120 },
                }),
                new Paragraph({
                  children: [
                    new TextRun({
                      text: executiveSummary,
                      size: 21,
                      color: "1E293B",
                      font: "Segoe UI",
                    }),
                  ],
                }),
              ],
            }),
          ],
        }),
      ],
    }),

    new Paragraph({ spacing: { after: 300 } }),
  ];

  // Dynamic Sections
  for (const sec of sections) {
    docChildren.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [
          new TextRun({
            text: sec.heading,
            bold: true,
            size: 32, // 16pt
            color: "0F172A",
            font: "Segoe UI",
          }),
        ],
        spacing: { before: 280, after: 140 },
      })
    );

    for (const p of sec.paragraphs) {
      docChildren.push(
        new Paragraph({
          children: [
            new TextRun({
              text: p,
              size: 22, // 11pt
              color: "334155",
              font: "Segoe UI",
            }),
          ],
          spacing: { after: 140 },
        })
      );
    }

    if (sec.bulletPoints && sec.bulletPoints.length > 0) {
      for (const bp of sec.bulletPoints) {
        docChildren.push(
          new Paragraph({
            bullet: { level: 0 },
            children: [
              new TextRun({
                text: bp,
                size: 22,
                color: "334155",
                font: "Segoe UI",
              }),
            ],
            spacing: { after: 80 },
          })
        );
      }
    }
  }

  // Data Table (if provided)
  if (tableData && tableData.headers.length > 0) {
    docChildren.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [
          new TextRun({
            text: "Operational Metrics & Benchmarks",
            bold: true,
            size: 26,
            color: "0F172A",
            font: "Segoe UI",
          }),
        ],
        spacing: { before: 300, after: 160 },
      })
    );

    const headerRow = new TableRow({
      tableHeader: true,
      children: tableData.headers.map(
        (h) =>
          new TableCell({
            borders: tableBorderLight,
            shading: { type: ShadingType.CLEAR, fill: "0F172A" },
            margins: { top: 120, bottom: 120, left: 160, right: 160 },
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: h,
                    bold: true,
                    size: 19,
                    color: "FFFFFF",
                    font: "Segoe UI",
                  }),
                ],
              }),
            ],
          })
      ),
    });

    const dataRows = tableData.rows.map((row, idx) => {
      const isAlt = idx % 2 === 1;
      return new TableRow({
        children: row.map(
          (cell) =>
            new TableCell({
              borders: tableBorderLight,
              shading: { type: ShadingType.CLEAR, fill: isAlt ? "F1F5F9" : "FFFFFF" },
              margins: { top: 100, bottom: 100, left: 140, right: 140 },
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: cell,
                      size: 20,
                      color: "334155",
                      font: "Segoe UI",
                    }),
                  ],
                }),
              ],
            })
        ),
      });
    });

    docChildren.push(
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [headerRow, ...dataRows],
      })
    );
    docChildren.push(new Paragraph({ spacing: { after: 300 } }));
  }

  // Recommended Action Items
  if (actionItems.length > 0) {
    docChildren.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [
          new TextRun({
            text: "Strategic Governance Action Items",
            bold: true,
            size: 26,
            color: "0F172A",
            font: "Segoe UI",
          }),
        ],
        spacing: { before: 260, after: 140 },
      })
    );

    for (const item of actionItems) {
      docChildren.push(
        new Paragraph({
          bullet: { level: 0 },
          children: [
            new TextRun({
              text: item,
              size: 21,
              color: "1E293B",
              font: "Segoe UI",
            }),
          ],
          spacing: { after: 100 },
        })
      );
    }
  }

  // Cryptographic Proof Sign-off
  docChildren.push(
    new Paragraph({ spacing: { before: 400 } }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({
          children: [
            new TableCell({
              borders: tableBorderLight,
              shading: { type: ShadingType.CLEAR, fill: "F8FAFC" },
              margins: { top: 140, bottom: 140, left: 160, right: 160 },
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: "CRYPTOGRAPHIC INTEGRITY & ZERO-TRUST ATTESTATION",
                      bold: true,
                      size: 16,
                      color: "0891B2",
                      font: "Consolas",
                    }),
                  ],
                  spacing: { after: 60 },
                }),
                new Paragraph({
                  children: [
                    new TextRun({
                      text: `SHA-256 Checksum: ${sha256Hash}\nZero-Trust Vault Status: VERIFIED_TAMPER_PROOF\nAI Governance Model: Constitution-Compliant Execution`,
                      size: 16,
                      color: "64748B",
                      font: "Consolas",
                    }),
                  ],
                }),
              ],
            }),
          ],
        }),
      ],
    })
  );

  const doc = new Document({
    sections: [
      {
        properties: {},
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: "NEXA AI Sovereign OS  •  Page ",
                    size: 16,
                    color: "94A3B8",
                  }),
                  new TextRun({
                    children: [PageNumber.CURRENT],
                    size: 16,
                    color: "94A3B8",
                  }),
                  new TextRun({
                    text: " of ",
                    size: 16,
                    color: "94A3B8",
                  }),
                  new TextRun({
                    children: [PageNumber.TOTAL_PAGES],
                    size: 16,
                    color: "94A3B8",
                  }),
                ],
              }),
            ],
          }),
        },
        children: docChildren,
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return { buffer, hash: sha256Hash };
}
